---

docker_host_cacert: null
docker_host_cert: null
docker_host_cert_path: "{{ ansible_user_dir }}/.docker"
docker_host_interfaces: []
docker_host_key: null
docker_host_tls: no
docker_host_tlsverify: no

