---

- name: bash_profile template
  template:
    src: bash_profile.j2
    dest: ~/.bash_profile
    mode: 0644
    force: no
    backup: yes

- name: copy gitexcludes
  copy:
    src: gitexcludes
    dest: ~/.gitexcludes
    mode: 0755
    force: no
    backup: yes


- name: gitconfig template
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0755
    force: no
    backup: yes

