---

- hosts: docker_hosts
  tasks:
    - name: remove containers
      docker_container:
        name: '{{ item }}'
        state: absent
      with_inventory_hostnames: docker_containers
      when: hostvars[item].image is defined
      tags:
        - recreate_containers

    - name: start containers
      docker_container:
        name: "{{ item }}"
        image: "{{ hostvars[item].image }}"
        command: tail -f /dev/null
        state: started
      with_inventory_hostnames: docker_containers
      when: hostvars[item].image is defined

- hosts: docker_containers
  gather_facts: no
  tasks:
    - name: raw install python
      raw: '{{ raw_install_python }}'
      when: raw_install_python is defined

