---

- hosts: docker_hosts
  tasks:
    - name: start containers
      docker_container:
        name: "{{ item }}"
        hostname: "{{ item }}"
        image: "{{ hostvars[item].image }}"
        command: tail -f /dev/null
        state: started
        recreate: "{{ hostvars[item].docker_containers_recreate | default('no') }}"
      with_inventory_hostnames: docker_containers
      when: hostvars[item].image is defined

- hosts: docker_containers
  gather_facts: no
  tasks:
    - name: raw install python
      raw: '{{ raw_install_python }}'
      when: raw_install_python is defined

