---

- hosts: localhost
  tasks:
    - name: start dojo container
      docker_container:
        name: dojo
        hostname: dojo
        image: ubuntu:latest
        command: tail -f /dev/null
        state: started
        exposed_ports:
          - "22"
          - "8000"
        published_ports:
          - "127.0.0.1:2222:22"
          - "127.0.0.1:8000:8000"
        volumes:
          - "{{ ansible_user_dir }}/code/contrib/django-DefectDojo:/opt/django-DefectDojo"
        recreate: "{{ recreate | default('no') }}"

- hosts: dojo
  gather_facts: no
  vars:
    common:
      install_pexpect: yes
      configure_ssh: yes
  pre_tasks:
    - block:
      - name: gather facts
        setup: {}
      rescue:
      - name: raw install python
        raw: "apt-get update && apt-get install -y python"
      - name: re-gather facts
        setup: {}
  roles:
    - common
    - defect-dojo

