---

- hosts: docker_hosts
  vars:
    jenkins_host_key: '{{ ansible_user_dir }}/jenkins-host-key.pem'
    jenkins_host_cert: '{{ ansible_user_dir }}/jenkins-host-cert.pem'

  tasks:
    - name: create self-signed certificate
      include_role:
        name: self-signer
      vars:
        ca_key: '{{ ansible_user_dir }}/{{ ca_fqdn }}-ca-key.pem'
        ca_cert: '{{ ansible_user_dir }}/{{ ca_fqdn }}-ca-cert.pem'
        ca_fqdn: "{{ ansible_domain | default(ansible_hostname + '.local', true) }}"
        ca_subj: "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organization }}/OU={{ organizational_unit }}/CN={{ ca_fqdn }}/emailAddress={{ email }}"
        host_key: '{{ jenkins_host_key }}'
        host_cert: '{{ jenkins_host_cert }}'
        host_fqdn: "jenkins.{{ ansible_domain | default(ansible_hostname + '.local', true) }}"

    - name: set jenkins cert and key ownership
      file:
        path: "{{ item }}"
        owner: 1000
        group: 1000
      with_items:
        - "{{ jenkins_host_key }}"
        - "{{ jenkins_host_cert }}"

    - name: start/create jenkins containers
      docker_container:
        name: jenkins
        hostname: jenkins
        image: jenkins
        recreate: yes
        state: started
        exposed_ports:
          - "8083"
        published_ports:
          - "0.0.0.0:8083:8083"
          - "0.0.0.0:50000:50000"
        volumes:
          - "jenkins_home:/var/jenkins_home"
          - "{{ jenkins_host_cert }}:/var/lib/jenkins/cert:ro"
          - "{{ jenkins_host_key }}:/var/lib/jenkins/pk:ro"
        env:
          JENKINS_OPTS: "--httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk"

- hosts: jenkins_servers
  tasks:
    - name: install jenkins plugins
      jenkins_plugin:
        jenkins_home: "{{ jenkins_servers.jenkins_home | default('/var/jenkins_home') }}"
        url: "https://localhost:8083"
        url_username: "{{ jenkins_servers.url_username }}"
        url_password: "{{ jenkins_servers.url_password }}"
        validate_certs: false
        state: latest
        name: artifactory

#- hosts: jenkins_servers
  #remote_user: root
  #roles:
    #- atlassian-plugin-sdk

