---

- hosts: docker_hosts
  tags: deploy
  become: true
  tasks:
    - name: create jenkins container
      docker_container:
        name: "{{ item }}"
        hostname: "{{ item }}"
        image: jenkins:latest
        pull: yes
        recreate: "{{ hostvars[item].docker_containers_recreate | default('no') }}"
        state: stopped
        exposed_ports:
          - "8083"
        published_ports:
          - "0.0.0.0:8083:8083"
          - "0.0.0.0:50000:50000"
        volumes:
          - "jenkins_home:/var/jenkins_home"
          - "/var/lib/jenkins"
        env:
          JENKINS_OPTS: "--httpPort=-1 --httpsPort=8083 --httpsCertificate=/var/lib/jenkins/cert.pem --httpsPrivateKey=/var/lib/jenkins/key.pem"
      with_inventory_hostnames: jenkins_servers

    - name: create temporary data_jenkins container
      docker_container:
        name: data_jenkins
        hostname: data_jenkins
        image: ubuntu:latest
        cleanup: yes
        detach: no
        command: >
          bash -c "
          cp /cert.pem /key.pem /var/lib/jenkins/;
          chown 1000:1000 /var/lib/jenkins/cert.pem /var/lib/jenkins/key.pem;
          chmod 400 /var/lib/jenkins/key.pem;
          chmod 444 /var/lib/jenkins/cert.pem"
        state: started
        user: root:root
        volumes:
          - "{{ docker_cert_path }}/cert.pem:/cert.pem:ro"
          - "{{ docker_cert_path }}/key.pem:/key.pem:ro"
        volumes_from:
          - "{{ item }}"
      with_inventory_hostnames: jenkins_servers

    - name: start jenkins container
      docker_container:
        name: "{{ item }}"
        state: started
      with_inventory_hostnames: jenkins_servers

- hosts: jenkins_servers
  gather_facts: no
  pre_tasks:
    - name: raw config
      raw: apt-get update && apt-get install -y python

    - name: gather facts
      setup: {}
  roles:
    - ansible
  #tasks:
    #- name: install jenkins plugins
      #jenkins_plugin:
        #jenkins_home: "{{ jenkins_servers.jenkins_home | default('/var/jenkins_home') }}"
        #url: "{{ jenkins_servers.url | default('https://localhost:8083') }}"
        #url_username: "{{ jenkins_servers.url_username }}"
        #url_password: "{{ jenkins_servers.url_password }}"
        ##validate_certs: false
        #state: latest
        #name: artifactory

