---

- include: containers.yml

- hosts: all:!stopped
  tasks:
      - group_by: key=os_{{ ansible_distribution }}
  tags:
      - always

- include: jenkins-servers.yml

#- include: macosx-workstations.yml

#- include: workstations.yml
