---

- include: containers.yml

- hosts: workstations
  tasks:
    - group_by: key={{ ansible_distribution|lower() }}_workstations
  tags:
    - always

- include: macosx-workstations.yml

- include: workstations.yml

- include: docker-hosts.yml

- include: jenkins-hosts.yml

