---

- name: create working dir
  file:
    path: '{{ working_dir }}'
    state: directory
    mode: 0750

- name: yum install openssl
  yum:
    name: openssl
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: generate CA private key
  command: >
    openssl genrsa -aes256
    -passout pass:{{ ca_password }}
    -out {{ ansible_fqdn }}-ca-key.pem 4096
  args:
    chdir: '{{ working_dir }}'
    creates: '{{ working_dir }}/{{ ansible_fqdn }}-ca-key.pem'

- name: set CA private key mode
  file:
    path: '{{ working_dir }}/{{ ansible_fqdn }}-ca-key.pem'
    mode: 0400

- name: generate CA public key
  command: >
    openssl req -new -x509 -days 365
    -key {{ ansible_fqdn }}-ca-key.pem -sha256
    -out {{ ansible_fqdn }}-ca.pem
    -passin pass:{{ ca_password }}
    -subj "/C={{ country }}/ST={{ state }}/L={{ locality }}/O={{ organization }}/OU={{ organizational_unit }}/CN={{ ansible_fqdn }}/emailAddress={{ email }}"
  args:
    chdir: '{{ working_dir }}'
    creates: '{{ working_dir }}/{{ ansible_fqdn }}-ca.pem'

- name: set CA public key mode
  file:
    path: '{{ working_dir }}/{{ ansible_fqdn }}-ca.pem'
    mode: 0444

- name: generate server private key
  #command: openssl genpkey -out {{ ansible_fqdn }}-key.pem -algorithm RSA -pkeyopt rsa_keygen_bits:4096
  command: openssl genrsa -out {{ ansible_fqdn }}-key.pem 4096
  args:
    chdir: '{{ working_dir }}'
    creates: '{{ working_dir }}/{{ ansible_fqdn }}-key.pem'

- name: set server private key mode
  file:
    path: '{{ working_dir }}/{{ ansible_fqdn }}-key.pem'
    mode: 0400

- name: create CSR
  command: >
    openssl req
    -subj "/CN={{ ansible_fqdn }}" -sha256 -new
    -key {{ ansible_fqdn }}-key.pem
    -out {{ ansible_fqdn }}.csr
  args:
    chdir: '{{ working_dir }}'
    creates: '{{ working_dir }}/{{ ansible_fqdn }}.csr'

- name: create extfile
  shell: echo subjectAltName = DNS:{{ ansible_fqdn }},IP:{{ ansible_default_ipv4.address }},IP:127.0.0.1 > {{ working_dir }}/extfile.cnf

- name: create signed server public key
  command: >
    openssl x509 -req -days 365 -sha256
    -in {{ ansible_fqdn }}.csr
    -CA {{ ansible_fqdn }}-ca.pem
    -CAkey {{ ansible_fqdn }}-ca-key.pem -CAcreateserial
    -out {{ ansible_fqdn }}-cert.pem
    -extfile extfile.cnf
    -passin pass:{{ ca_password }}
  args:
    chdir: '{{ working_dir }}'
    creates: '{{ working_dir }}/{{ ansible_fqdn }}-cert.pem'

- name: set server public key mode
  file:
    path: '{{ working_dir }}/{{ ansible_fqdn }}-cert.pem'
    mode: 0444

