---

- name: include common role
  include_role:
    name: common

- name: install docker
  include: "{{ ansible_pkg_mgr }}-install.yml"

- name: enable docker service
  service:
    name: docker
    enabled: yes

- name: pip install docker
  pip:
    name: docker
    state: latest

- name: create docker dot dir
  file:
    path: "{{ docker_host_cert_path }}"
    state: directory
    mode: 0700

- name: copy docker cacert
  copy:
    backup: yes
    content: "{{ docker_host_cacert }}"
    dest: "{{ docker_host_cert_path }}/ca.pem"
    #group: docker
    mode: 0444
  when: docker_host_tlsverify|bool

- name: copy docker cert
  copy:
    backup: yes
    content: "{{ docker_host_cert }}"
    dest: "{{ docker_host_cert_path }}/cert.pem"
    #group: docker
    mode: 0444
  when: docker_host_tlsverify|bool or docker_host_tls|bool

- name: copy docker key
  copy:
    backup: yes
    content: "{{ docker_host_key }}"
    dest: "{{ docker_host_cert_path }}/key.pem"
    #group: docker
    mode: 0400
  when: docker_host_tlsverify|bool or docker_host_tls|bool

- name: create /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: 0755
    owner: root
    group: root

- name: template daemon.json
  template:
    backup: yes
    dest: /etc/docker/daemon.json
    group: root
    owner: root
    mode: 0644
    src: daemon.json.j2
  notify: restart docker daemon

- name: firewalld add docker0 interface to trusted zone
  firewalld:
    immediate: yes
    interface: docker0
    permanent: yes
    state: enabled
    zone: trusted
  notify:
    - restart firewalld
    - restart docker daemon

# NOTE: no support yet for opening non-tls port
- name: firewalld add daemon tls port 2376 to default zone
  firewalld:
    immediate: yes
    port: 2376/tcp
    permanent: yes
    state: enabled
  when: docker_host_tlsverify|bool or docker_host_tls|bool
  notify:
    - restart firewalld
    - restart docker daemon

