---

- block:
  - name: create ssh directory
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: copy read-only ssh private key
    copy:
      src: ~/.ssh/{{ ssh_key_name }}
      dest: ~/.ssh/{{ ssh_key_name }}
      mode: 0600

  - name: copy read-only ssh public key
    copy:
      src: ~/.ssh/{{ ssh_key_name }}.pub
      dest: ~/.ssh/{{ ssh_key_name }}.pub
      mode: 0644

  - name: create code directory
    file:
      path: ~/code
      state: directory
      mode: 0740

  - name: clone dev-environment
    git:
      repo: git@bitbucket.org:milo-minderbinder/dev-environment.git
      dest: ~/code/dev-environment
      accept_hostkey: yes
      key_file: ~/.ssh/{{ ssh_key_name }}

#always:
  #- name: remove ssh private key
    #file:
      #path: ~/.ssh/{{ ssh_key_name }}
      #state: absent

  #- name: remove ssh public key
    #file:
      #path: ~/.ssh/{{ ssh_key_name }}.pub
      #state: absent

