---

- block:
  - name: get node setup script
    get_url:
      url: https://deb.nodesource.com/setup_{{ node_version }}.x
      dest: /tmp/node_setup_{{ node_version }}.x.bash
      mode: 0400

  - name: execute node setup script
    shell: bash /tmp/node_setup_{{ node_version }}.x.bash

  - name: install nodejs apt
    apt: name=nodejs state=latest update_cache=yes

  always:
    - name: remove node setup script
      file: path=/tmp/node_setup_{{ node_version }}.x.bash state=absent

