---

- block:
  - name: epel repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: installed

  - name: get node setup script
    get_url:
      url: https://rpm.nodesource.com/setup_{{ node_version }}.x
      dest: /tmp/node_setup_{{ node_version }}.x.bash
      mode: 0400

  - name: execute node setup script
    shell: bash /tmp/node_setup_{{ node_version }}.x.bash

  - name: install nodejs yum
    yum: name=nodejs state=latest update_cache=yes

  always:
    - name: remove node setup script
      file: path=/tmp/node_setup_{{ node_version }}.x.bash state=absent

