---

- hosts: docker_hosts
  become: true
  vars:
    backup_dir: "{{ ansible_user_dir }}/backups"
    backup_file: "jenkins-{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
  tasks:
    - name: create backup dir
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: 0750

    - name: create backup
      command: tar czf {{ backup_dir }}/{{ backup_file }} jenkins/
      args:
        chdir: /var/lib

    - name: set backup file mode
      file:
        path: "{{ backup_dir }}/{{ backup_file }}"
        state: file
        mode: 0440

    - name: temporarily move backup
      command: mv '{{ backup_dir }}/{{ backup_file }}' '/tmp/{{ backup_file }}'

    - name: set temp backup file mode and owner
      file:
        path: /tmp/{{ backup_file }}
        state: file
        mode: 0440
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: fetch backup file
      fetch:
        dest: "/Users/{{ ansible_user }}/Documents/"
        flat: yes
        src: /tmp/{{ backup_file }}
      become: false

    - name: move backup to backup dir
      command: mv '/tmp/{{ backup_file }}' '{{ backup_dir }}/{{ backup_file }}'

    - name: reset backup file mode and owner
      file:
        path: "{{ backup_dir }}/{{ backup_file }}"
        state: file
        mode: 0440
        owner: root
        group: root

