---

- hosts: docker_hosts
  become: true
  vars:
    backup_dir: "{{ ansible_user_dir }}/backups"
    backup_file: "jenkins-{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
  tasks:
    - name: create backup dir
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: 0750

    #- name: run backup container
      #docker_container:
        #name: backup_jenkins
        #image: ubuntu:latest
        #state: started
        #cleanup: yes
        #detach: no
        #volumes:
          #- "{{ backup_dir }}:/backups"
        #volumes_from:
          #- jenkins
        #user: root:root
        #command: tar czf /backups/{{ backup_file }} /var/jenkins_home/

    - name: create backup
      command: tar czf {{ backup_dir }}/{{ backup_file }} /var/lib/jenkins/

    - name: set backup file mode
      file:
        path: "{{ backup_dir }}/{{ backup_file }}"
        state: file
        mode: 0440

