---

all:
  children:
    workstations:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
    running:
    stopped:
    docker_hosts:
    docker_containers:
      vars:
        ansible_user: root
        ansible_connection: docker
        ansible_host: "{{ inventory_hostname }}"
      children:
        running:
        stopped:

