---

all:
  children:
    workstations:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
    volatile_containers:
      vars:
        docker_containers_volatile: yes
        #docker_containers_recreate: yes
      hosts:
        centos7:
          docker_containers_image: centos:7
        ubuntu:
          docker_containers_image: ubuntu:latest
          docker_containers_raw: apt-get update && apt-get install -y python
        fedora:
          docker_containers_image: fedora:latest
          docker_containers_raw: dnf install -y python
    running:
    stopped:
    docker_hosts:
    docker_containers:
      vars:
        ansible_user: root
        ansible_connection: docker
        ansible_host: "{{ inventory_hostname }}"
        docker_containers_volatile: no
      children:
        running:
        stopped:
        volatile_containers:
        jenkins_servers:

