---

all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
  children:
    workstations:
    jenkins_slaves:
    jenkins_servers:
    running:
    stopped:
    docker_hosts:
    temporary_containers:
      vars:
        docker_containers_temporary: yes
        docker_containers_command: tail -f /dev/null
        #docker_containers_recreate: yes
    docker_containers:
      vars:
        ansible_user: root
        ansible_connection: docker
        ansible_host: "{{ inventory_hostname }}"
        docker_containers_temporary: no
      children:
        running:
        stopped:
        temporary_containers:

