---

all:
  children:
    running:
    stopped:
    docker_hosts:
      hosts:
        unix://var/run/docker.sock:
          ansible_python_interpreter: /usr/local/bin/python
          ansible_connection: local
    docker_containers:
      vars:
        ansible_connection: docker
      hosts:
        baseimage:
          image: mminderbinder/baseimage
          raw_install_python: apt-get update && apt-get install -y python
        fedora25:
          image: fedora:25
          raw_install_python: dnf install -y python27
        centos7:
          image: centos:7
      children:
        running:
        stopped:
    jenkins_servers:
      hosts:
        baseimage:
        centos7:
        jenkins_jenkins_1:
        fedora25:

