---

all:
  children:
    workstations:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_connection: local
    running:
    stopped:
    docker_hosts:
    docker_containers:
      vars:
        ansible_connection: docker
      children:
        running:
        stopped:
    jenkins_servers:
      hosts:
        jenkins_jenkins_1:

