---

- name: include ansible_pkg_mgr packages
  include: "{{ ansible_pkg_mgr }}-packages.yml"

- name: install ansible devel with pip
  pip:
    name: "git+git://github.com/ansible/ansible.git@devel#egg=ansible"
    state: latest

