---

- name: update cache and upgrade all installed packages
  apt: update_cache=yes upgrade=dist

- name: install common packages
  apt: name={{ item }} state=latest
  with_items:
    - python
    - iputils-ping
    #- python-pip

- name: install openssh-server
  apt: name=openssh-server state=latest
  when: common.configure_ssh | default('no') | bool

# At least for Ubuntu 14.04 LTS, the python-pip package will fail to install some
# packages, like cryptography, due to issues with  setuptools, which pip tries to
# build from source dist, which is no longer supported.
# May be possible to fix by manually installing the packaging, appdirs, and six python
# packages, but it seems the easier fix is to just install pip using get-pip.py.
# see: https://github.com/pypa/setuptools/issues/937#issuecomment-274629937
- name: purge python-pip package
  apt: name=python-pip purge=yes state=absent

- name: install pip with get-pip.py
  include: get-pip-install.yml

# see: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
- name: install cryptography package dependencies
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
  when: common.sni_fix | default('no') | bool

