---

- name: upgrade all installed packages
  dnf: name='*' state=latest

- name: install common packages
  dnf: name={{ item }} state=latest
  with_items:
    - python
    - iputils

- name: install openssh-server
  dnf: name=openssh-server state=latest
  when: common.configure_ssh | default('no') | bool

- name: upgrade pip
  pip: name=pip state=latest

# see: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
- name: install cryptography package dependencies
  dnf: name={{ item }} state=latest
  with_items:
    - gcc
    - libffi-devel
    - openssl-devel
    - python-devel
    - redhat-rpm-config
  when: common.sni_fix | default('no') | bool
#when: ansible_python_version|version_compare('2.7.9', '<')

