---

- name: install python
  include: "{{ ansible_pkg_mgr}}-packages.yml"

- name: debug common vars
  debug:
    var: common

# note: wheel dropped support for Python < 2.7 after wheel 0.29.0
- name: pip install wheel
  pip:
    name: wheel
    state: "{{ (ansible_python_version|version_compare('2.7', '<'))|ternary('present', 'latest') }}"
    version: "{{ (ansible_python_version|version_compare('2.7', '<'))|ternary('0.29.0', omit) }}"

- name: install urllib3 with secure extra to fix SNI
  pip: name=urllib3[secure] state=latest
  when: common.sni_fix | default('no') | bool
  #when: ansible_python_version|version_compare('2.7.9', '<')

- name: install pip dependency for expect module
  pip:
    name: pexpect
    state: latest
  when: common.install_pexpect | default('no') | bool

- block:
  - name: template sshd_config
    template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
      mode: 0644
      backup: yes
    notify: reload sshd

  - name: set authorized_keys
    authorized_key:
      user: "{{ ansible_user_id }}"
      exclusive: yes
      key: "{{ common.configure_ssh_key | default('https://github.com/milo-minderbinder.keys') }}"
      state: present
  when: common.configure_ssh | default('no') | bool

