---

- name: update cache and upgrade all installed packages
  yum: name='*' update_cache=yes state=latest

- name: add epel repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    update_cache: yes

- name: install common packages
  yum: name={{ item }} state=latest
  with_items:
    - python
    - iputils

- name: install openssh-server
  yum: name=openssh-server state=latest
  when: common.configure_ssh | default('no') | bool

- name: remove python-pip package
  yum: name=python-pip state=absent

- name: install pip with get-pip.py
  include: get-pip-install.yml

# see: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
- name: install cryptography package dependencies
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - libffi-devel
    - openssl-devel
    - python-devel
  when: common.sni_fix | default('no') | bool
  #when: ansible_python_version|version_compare('2.7.9', '<')

