---

- name: add epel repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: installed
    update_cache: yes
  become: true

- name: install dependencies yum
  yum:
    name:
      - automake
      - cmake
      - gcc
      - gcc-c++
      - git
      - kernel-devel
      - make
      - python-devel
      - python36-devel
      - vim-enhanced
    state: latest
    update_cache: yes
  become: true

